### ISSUE TITLE
Is it possible to run a driver/drivers in headless mode?

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/xenon#1] opened 2020-09-11 15:02 UTC
Hey @stevepryde,
It seems to me like a good library/crate/binary.

It is possible to pass any capabilities/settings to the `webdriver`s or at least have a custom default settings such as `--headless` arg for `geckodrver` or `chromedriver`?

I've played with the code in order to have it done but haven't succeeded :( 

I was experimenting with the data here.

https://github.com/stevepryde/xenon/blob/91fef580287c438b43d3aacf545d5282e95f346f/src/server.rs#L248-L249  
https://github.com/stevepryde/xenon/blob/91fef580287c438b43d3aacf545d5282e95f346f/src/session.rs#L113-L118

Thanks

**Comment by stevepryde** [comment] 2020-09-12 00:51
I've had a look into this and confirmed that the headless flag is not working.

After some investigation I discovered that the `goog:chromeOptions` JSON is indeed sent with the `alwaysMatch` capabilities, so I'll need to update Xenon to pass those through.

The reason it strips some capabilities out there is because if we do the filtering ourselves in Xenon, we don't want `chromedriver` also doing its own filtering and deciding not to run the session we send to it.

It's easy enough to just pick out the `goog:chromeOptions` and `moz:firefoxOptions` keys and pass those through specifically, or alternatively I can try just passing through the `alwaysMatch` JSON verbatim and let it fail if the client does something wrong. The latter is probably the better option.

**Comment by stevepryde** [comment] 2020-09-12 01:05
And confirmed that works if I pass through all of the capabilities verbatim.
I've pushed the fix to latest main branch so if you pull that and try again it should hopefully work. Let me know how it goes.

I have not tested the impact this has on filtering. We can address that later if there is an issue (perhaps we can strip out the `browserName`, `browserVersion` and `platformName` if we need to).

**Comment by stevepryde** [comment] 2020-09-12 01:08
Also consider running via `xvfb` instead (see instructions at the bottom of the README) which allows you to vnc in and view the session if you need to.

Either way you would still need the above fix in order to pass through any other chrome/firefox options

**Comment by zhiburt** [comment] 2020-09-14 08:50
I can confirm that after https://github.com/stevepryde/xenon/commit/3b106ec15d21448b9198f7a2e474e21c45e5b0cd headless works :+1:

**Closed as completed** 2020-09-14 08:50 UTC
